tasks:
  default: # must be the name returned by the overworld
    onboard_world: TelegramBotOnboardWorld
    task_world: TelegramBotChatTaskWorld
    timeout: 1
    agents_required: 1
task_name: chatbot
world_module: tasks.chatbot.worlds
overworld: TelegramOverworld
max_workers: 30
opt:
  force_telegram_bot_token: False  # for read token from the file
  models:
    blender_90M:
      model: transformer/generator
      model_file: zoo:blender/blender_90M/model
      interactive_mode: True
      no_cuda: True